$(document).ready(function(){
    $('#menu-btn').click(function(){
        $('.navbar').toggleClass('active')
        $('#menu-btn').toggleClass('fa-times')
    })
    $(window).scroll(function(){
        $('.navbar').removeClass('active')
        $('#menu-btn').removeClass('fa-times')
    })
})